Debug cicd path

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -27,6 +27,11 @@ jobs:
         run: |
           gcloud container clusters get-credentials learn-cluster \
             --zone asia-south1-a
+       - name: Debug workspace
+        run: |
+          pwd
+          ls -la
+          ls -la cicd-chart || echo "cicd-chart missing"
 
       - name: Deploy using Helm
         run: |
